name: CI/CD

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
    types: [opened, synchronize, reopened, edited, ready_for_review]

jobs:
  tests:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"

      - name: Install pipenv
        run: |
          python -m pip install --upgrade pip pipenv wheel pytest
          pip install -r ./requirements.txt

      - name: Test with pytest
        run: |
          python -m pytest tests/*  

  lint:
    - name: Install pipenv
      run: |
        python -m pip install black

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run Black Linter
        run:
          black myproject/*.py
